CREATE TABLE FIO_MEN
(
    FIRST_NAME NVARCHAR2(20),
    LAST_NAME NVARCHAR2(20),
    MIDDLE_NAME NVARCHAR2(20)
);

DROP TABLE FIO_MEN;


CREATE TABLE FIO_WOMEN
(
    FIRST_NAME NVARCHAR2(20),
    LAST_NAME NVARCHAR2(20),
    MIDDLE_NAME NVARCHAR2(20)
);

DROP TABLE FIO_WOMEN;

BEGIN
    INSERT INTO FIO_MEN (FIRST_NAME, LAST_NAME, MIDDLE_NAME) VALUES ('Адам', 'Голубев', 'Егорович');
    INSERT INTO FIO_MEN (FIRST_NAME, LAST_NAME, MIDDLE_NAME) VALUES ('Тимофей', 'Воробьев', 'Фёдорович');
    INSERT INTO FIO_MEN (FIRST_NAME, LAST_NAME, MIDDLE_NAME) VALUES ('Артём', 'Попов', 'Павлович');
    INSERT INTO FIO_MEN (FIRST_NAME, LAST_NAME, MIDDLE_NAME) VALUES ('Михаил', 'Новиков', 'Михайлович');
    INSERT INTO FIO_MEN (FIRST_NAME, LAST_NAME, MIDDLE_NAME) VALUES ('Пётр', 'Егоров', 'Матвеевич');
    INSERT INTO FIO_MEN (FIRST_NAME, LAST_NAME, MIDDLE_NAME) VALUES ('Семён', 'Алексеев', 'Александрович');
    INSERT INTO FIO_MEN (FIRST_NAME, LAST_NAME, MIDDLE_NAME) VALUES ('Иван', 'Демидов', 'Даниилович');
    INSERT INTO FIO_MEN (FIRST_NAME, LAST_NAME, MIDDLE_NAME) VALUES ('Матвей', 'Данилов', 'Владиславович');
    
    INSERT INTO FIO_MEN (FIRST_NAME, LAST_NAME, MIDDLE_NAME) VALUES ('Сергей', 'Вишняков', 'Сергеевич');
    INSERT INTO FIO_MEN (FIRST_NAME, LAST_NAME, MIDDLE_NAME) VALUES ('Юрий', 'Выдрин', 'Юриьевич');
    INSERT INTO FIO_MEN (FIRST_NAME, LAST_NAME, MIDDLE_NAME) VALUES ('Степан', 'Ермолин', 'Степанович');
    INSERT INTO FIO_MEN (FIRST_NAME, LAST_NAME, MIDDLE_NAME) VALUES ('Пётр', 'Гуркин', 'Петрович');
    INSERT INTO FIO_MEN (FIRST_NAME, LAST_NAME, MIDDLE_NAME) VALUES ('Владислав', 'Бодрев', 'Владиславович');
    INSERT INTO FIO_MEN (FIRST_NAME, LAST_NAME, MIDDLE_NAME) VALUES ('Дмитрий', 'Зенько', 'Дмитриевич');
    INSERT INTO FIO_MEN (FIRST_NAME, LAST_NAME, MIDDLE_NAME) VALUES ('Евгений', 'Мирошников', 'Евгеньевич');
    INSERT INTO FIO_MEN (FIRST_NAME, LAST_NAME, MIDDLE_NAME) VALUES ('Даниил', 'Харитонов', 'Даниилович');
    INSERT INTO FIO_MEN (FIRST_NAME, LAST_NAME, MIDDLE_NAME) VALUES ('Артём', 'Абрамович', 'Артёмович');
    INSERT INTO FIO_MEN (FIRST_NAME, LAST_NAME, MIDDLE_NAME) VALUES ('Андрей', 'Кулинич', 'Андреевич');
    INSERT INTO FIO_MEN (FIRST_NAME, LAST_NAME, MIDDLE_NAME) VALUES ('Павел', 'Костылев', 'Павлович');
    INSERT INTO FIO_MEN (FIRST_NAME, LAST_NAME, MIDDLE_NAME) VALUES ('Валерий', 'Шарипов', 'Валерьевич');
    INSERT INTO FIO_MEN (FIRST_NAME, LAST_NAME, MIDDLE_NAME) VALUES ('Иван', 'Залуцкий', 'Иванович');
    INSERT INTO FIO_MEN (FIRST_NAME, LAST_NAME, MIDDLE_NAME) VALUES ('Кирилл', 'Кухарский', 'Кириллович');
    INSERT INTO FIO_MEN (FIRST_NAME, LAST_NAME, MIDDLE_NAME) VALUES ('Никита', 'Михайлов', 'Никитьевич');
    INSERT INTO FIO_MEN (FIRST_NAME, LAST_NAME, MIDDLE_NAME) VALUES ('Егор', 'Тесленко', 'Егорович');
    INSERT INTO FIO_MEN (FIRST_NAME, LAST_NAME, MIDDLE_NAME) VALUES ('Филипп', 'Ищук', 'Филиппович');
    INSERT INTO FIO_MEN (FIRST_NAME, LAST_NAME, MIDDLE_NAME) VALUES ('Богдан', 'Сухарев', 'Богданович');
    INSERT INTO FIO_MEN (FIRST_NAME, LAST_NAME, MIDDLE_NAME) VALUES ('Ярослав', 'Демченко', 'Ярослав');
    INSERT INTO FIO_MEN (FIRST_NAME, LAST_NAME, MIDDLE_NAME) VALUES ('Климентий', 'Велетнюк', 'Климентьевич');
    INSERT INTO FIO_MEN (FIRST_NAME, LAST_NAME, MIDDLE_NAME) VALUES ('Святослав', 'Деревинский', 'Святослав');
    INSERT INTO FIO_MEN (FIRST_NAME, LAST_NAME, MIDDLE_NAME) VALUES ('Максим', 'Мороз', 'Максимович');
    INSERT INTO FIO_MEN (FIRST_NAME, LAST_NAME, MIDDLE_NAME) VALUES ('Денис', 'Ляшенко', 'Денисович');
    INSERT INTO FIO_MEN (FIRST_NAME, LAST_NAME, MIDDLE_NAME) VALUES ('Игорь', 'Оруджев', 'Игорьевич');
    INSERT INTO FIO_MEN (FIRST_NAME, LAST_NAME, MIDDLE_NAME) VALUES ('Матвей', 'Нагорный', 'Матвеевич');
    INSERT INTO FIO_MEN (FIRST_NAME, LAST_NAME, MIDDLE_NAME) VALUES ('Владимир', 'Варакута', 'Владимирович');
    INSERT INTO FIO_MEN (FIRST_NAME, LAST_NAME, MIDDLE_NAME) VALUES ('Михаил', 'Котенкович', 'Михаилович');
    
    INSERT INTO FIO_WOMEN (FIRST_NAME, LAST_NAME, MIDDLE_NAME) VALUES ('Валерия', 'Оруджева', 'Дмитриевна');
    INSERT INTO FIO_WOMEN (FIRST_NAME, LAST_NAME, MIDDLE_NAME) VALUES ('Дарья', 'Кравченко', 'Владимировна');
    INSERT INTO FIO_WOMEN (FIRST_NAME, LAST_NAME, MIDDLE_NAME) VALUES ('Вероника', 'Сухарева', 'Алексеевна');
    INSERT INTO FIO_WOMEN (FIRST_NAME, LAST_NAME, MIDDLE_NAME) VALUES ('Ирина', 'Мороз', 'Семёновна');
    INSERT INTO FIO_WOMEN (FIRST_NAME, LAST_NAME, MIDDLE_NAME) VALUES ('Валентина', 'Михайлова', 'Артёмовна');
    INSERT INTO FIO_WOMEN (FIRST_NAME, LAST_NAME, MIDDLE_NAME) VALUES ('Галина', 'Тесленко', 'Данииловна');
    INSERT INTO FIO_WOMEN (FIRST_NAME, LAST_NAME, MIDDLE_NAME) VALUES ('Анна', 'Потапович', 'Ильина');
    INSERT INTO FIO_WOMEN (FIRST_NAME, LAST_NAME, MIDDLE_NAME) VALUES ('Елена', 'Калакша', 'Александровна');
    INSERT INTO FIO_WOMEN (FIRST_NAME, LAST_NAME, MIDDLE_NAME) VALUES ('Татьяна', 'Кальчевская', 'Владиславовна');
    INSERT INTO FIO_WOMEN (FIRST_NAME, LAST_NAME, MIDDLE_NAME) VALUES ('Светлана', 'Жукова', 'Александровна');
    INSERT INTO FIO_WOMEN (FIRST_NAME, LAST_NAME, MIDDLE_NAME) VALUES ('Людмила', 'Трофимова', 'Дмитриевна');
    INSERT INTO FIO_WOMEN (FIRST_NAME, LAST_NAME, MIDDLE_NAME) VALUES ('Надежда', 'Абрамович', 'Александровна');
    INSERT INTO FIO_WOMEN (FIRST_NAME, LAST_NAME, MIDDLE_NAME) VALUES ('Любовь', 'Царёва', 'Александровна');
    INSERT INTO FIO_WOMEN (FIRST_NAME, LAST_NAME, MIDDLE_NAME) VALUES ('Екатерина', 'Черникова', 'Дмитриевна');
    INSERT INTO FIO_WOMEN (FIRST_NAME, LAST_NAME, MIDDLE_NAME) VALUES ('Евгения', 'Найден', 'Ильина');
    INSERT INTO FIO_WOMEN (FIRST_NAME, LAST_NAME, MIDDLE_NAME) VALUES ('Полина', 'Семенюк', 'Алексеевна');
    INSERT INTO FIO_WOMEN (FIRST_NAME, LAST_NAME, MIDDLE_NAME) VALUES ('Мария', 'Фалько', 'Викторовна');
    INSERT INTO FIO_WOMEN (FIRST_NAME, LAST_NAME, MIDDLE_NAME) VALUES ('Анастасия', 'Пак', 'Александровна');
    INSERT INTO FIO_WOMEN (FIRST_NAME, LAST_NAME, MIDDLE_NAME) VALUES ('Юлия', 'Лисовская', 'Викторовна');
    INSERT INTO FIO_WOMEN (FIRST_NAME, LAST_NAME, MIDDLE_NAME) VALUES ('Виктория', 'Кухаренко', 'Алексеевна');
    INSERT INTO FIO_WOMEN (FIRST_NAME, LAST_NAME, MIDDLE_NAME) VALUES ('Елизавета', 'Шаметько', 'Викторовна');
    INSERT INTO FIO_WOMEN (FIRST_NAME, LAST_NAME, MIDDLE_NAME) VALUES ('Ольга', 'Малько', 'Викторовна');
END;

COMMIT;

CREATE OR REPLACE FUNCTION FUNC_NAME_MEN
RETURN NVARCHAR2
IS 
NAME_MEN NVARCHAR2(20);
BEGIN
SELECT FIRST_NAME INTO NAME_MEN FROM(
SELECT FIRST_NAME FROM FIO_MEN ORDER BY DBMS_RANDOM.RANDOM)
FETCH FIRST 1 ROW ONLY;
RETURN NAME_MEN;
END;

CREATE OR REPLACE FUNCTION FUNC_SURNAME_MEN
RETURN NVARCHAR2
IS 
SURNAME_MEN NVARCHAR2(20);
BEGIN
SELECT LAST_NAME INTO SURNAME_MEN FROM (
SELECT LAST_NAME FROM FIO_MEN ORDER BY DBMS_RANDOM.RANDOM)
FETCH FIRST 1 ROW ONLY;
RETURN SURNAME_MEN;
END;

CREATE OR REPLACE FUNCTION FUNC_PATRONYMIC_MEN
RETURN NVARCHAR2
IS 
PATRONYMIC_MEN NVARCHAR2(20);
BEGIN
SELECT MIDDLE_NAME INTO PATRONYMIC_MEN FROM (
SELECT MIDDLE_NAME FROM FIO_MEN ORDER BY DBMS_RANDOM.RANDOM)
FETCH FIRST 1 ROW ONLY;
RETURN PATRONYMIC_MEN;
END;

CREATE OR REPLACE FUNCTION FUNC_NAME_WOMEN
RETURN NVARCHAR2
IS 
NAME_WOMEN NVARCHAR2(20);
BEGIN
SELECT FIRST_NAME INTO NAME_WOMEN FROM (
SELECT FIRST_NAME FROM FIO_WOMEN ORDER BY DBMS_RANDOM.RANDOM)
FETCH FIRST 1 ROW ONLY;
RETURN NAME_WOMEN;
END;

CREATE OR REPLACE FUNCTION FUNC_SURNAME_WOMEN
RETURN NVARCHAR2
IS 
SURNAME_WOMEN NVARCHAR2(20);
BEGIN
SELECT FIRST_NAME INTO SURNAME_WOMEN FROM (
SELECT FIRST_NAME FROM FIO_WOMEN ORDER BY DBMS_RANDOM.RANDOM)
FETCH FIRST 1 ROW ONLY;
RETURN SURNAME_WOMEN;
END;

CREATE OR REPLACE FUNCTION FUNC_PATRONYMIC_WOMEN
RETURN NVARCHAR2
IS 
PATRONYMIC_WOMEN NVARCHAR2(20);
BEGIN
SELECT MIDDLE_NAME INTO PATRONYMIC_WOMEN FROM (
SELECT MIDDLE_NAME FROM FIO_WOMEN ORDER BY DBMS_RANDOM.RANDOM)
FETCH FIRST 1 ROW ONLY;
RETURN PATRONYMIC_WOMEN;
END;

CREATE TABLE DLPASSPORT
(
LETTERS NVARCHAR2(2)
);
BEGIN
INSERT INTO DLPASSPORT VALUES ('MP');
INSERT INTO DLPASSPORT VALUES ('BP');
INSERT INTO DLPASSPORT VALUES ('HP');
INSERT INTO DLPASSPORT VALUES ('PH');
INSERT INTO DLPASSPORT VALUES ('AP');
INSERT INTO DLPASSPORT VALUES ('AM');
END;

COMMIT;

DROP TABLE DLPASSPORT;

CREATE OR REPLACE FUNCTION RPASSPORT
RETURN NVARCHAR2
IS
LPASSPORT NVARCHAR2(2);
NPASSPORT NUMBER;
FPASSPORT NVARCHAR2(9);
BEGIN 
SELECT LETTERS INTO LPASSPORT FROM(
SELECT LETTERS FROM DLPASSPORT
WHERE LETTERS IS NOT NULL
ORDER BY DBMS_RANDOM.RANDOM)
FETCH FIRST 1 ROW ONLY;
SELECT DBMS_RANDOM.VALUE(0000000, 9999999) NUM INTO NPASSPORT FROM DUAL;
NPASSPORT := ROUND(NPASSPORT);
FPASSPORT := CONCAT(LPASSPORT, NPASSPORT);
RETURN FPASSPORT;
END;

CREATE TABLE OPER 
(
NUMBER_O NVARCHAR2(2)
);
BEGIN
INSERT INTO OPER VALUES('44');
INSERT INTO OPER VALUES('33');
INSERT INTO OPER VALUES('29');
INSERT INTO OPER VALUES('17');
END;

COMMIT;

DROP TABLE OPER;

CREATE OR REPLACE FUNCTION RAND_PHONE_NUMBER
RETURN NVARCHAR2
IS 
COUNTRY_CODE NVARCHAR2(4) := '+375';
OPERATOR_CODE NVARCHAR2(2);
PHONE_CODE NVARCHAR2(50);
PHONE_NUMBER NVARCHAR2(100);
BEGIN
SELECT NUMBER_O INTO OPERATOR_CODE FROM (
SELECT NUMBER_O FROM OPER
ORDER BY DBMS_RANDOM.RANDOM)
FETCH FIRST 1 ROW ONLY;
SELECT DBMS_RANDOM.VALUE(1000000, 9999999) NUM INTO PHONE_CODE FROM DUAL;
PHONE_CODE := ROUND(PHONE_CODE);
PHONE_NUMBER := CONCAT(CONCAT(COUNTRY_CODE, OPERATOR_CODE), PHONE_CODE);
RETURN PHONE_NUMBER;
END;


CREATE TABLE ADDRESS_INFO 
(
URBAN_AREA NVARCHAR2(30),
CITY NVARCHAR2(30),
VILLAGE NVARCHAR2(30),
STREET NVARCHAR2(30) 
);

DROP TABLE ADDRESS_INFO;

BEGIN
    INSERT INTO ADDRESS_INFO (URBAN_AREA, CITY, VILLAGE, STREET) VALUES ('Минская область', 'Минск', '', 'Свердлова');
    INSERT INTO ADDRESS_INFO (URBAN_AREA, CITY, VILLAGE, STREET) VALUES ('Минская область', 'Минск', '', 'Шамякина');
    INSERT INTO ADDRESS_INFO (URBAN_AREA, CITY, VILLAGE, STREET) VALUES ('Минская область', 'Минск', '', 'Шаранговича');
    INSERT INTO ADDRESS_INFO (URBAN_AREA, CITY, VILLAGE, STREET) VALUES ('Минская область', 'Минск', '', 'Яна Чечоты');
    INSERT INTO ADDRESS_INFO (URBAN_AREA, CITY, VILLAGE, STREET) VALUES ('Минская область', 'Минск', '', 'Ежи Гедройца');
    INSERT INTO ADDRESS_INFO (URBAN_AREA, CITY, VILLAGE, STREET) VALUES ('Минская область', 'Минск', '', 'Столичная');
    INSERT INTO ADDRESS_INFO (URBAN_AREA, CITY, VILLAGE, STREET) VALUES ('Минская область', 'Минск', '', 'Горецкого');
    INSERT INTO ADDRESS_INFO (URBAN_AREA, CITY, VILLAGE, STREET) VALUES ('Минская область', 'Минск', '', 'Янковского');
    INSERT INTO ADDRESS_INFO (URBAN_AREA, CITY, VILLAGE, STREET) VALUES ('Минская область', 'Минск', '', 'Карла Маркса');
    INSERT INTO ADDRESS_INFO (URBAN_AREA, CITY, VILLAGE, STREET) VALUES ('Минская область', 'Минск', '', 'Притыцкого');
    INSERT INTO ADDRESS_INFO (URBAN_AREA, CITY, VILLAGE, STREET) VALUES ('Минская область', 'Минск', '', 'Дзержинского');
    INSERT INTO ADDRESS_INFO (URBAN_AREA, CITY, VILLAGE, STREET) VALUES ('Минская область', 'Минск', '', 'Каролинская');
    INSERT INTO ADDRESS_INFO (URBAN_AREA, CITY, VILLAGE, STREET) VALUES ('Минская область', 'Минск', '', 'Космонатвтов');
    INSERT INTO ADDRESS_INFO (URBAN_AREA, CITY, VILLAGE, STREET) VALUES ('Минская область', 'Минск', '', 'Октябрьская');
    INSERT INTO ADDRESS_INFO (URBAN_AREA, CITY, VILLAGE, STREET) VALUES ('Минская область', 'Минск', '', 'Белорусская');
    INSERT INTO ADDRESS_INFO (URBAN_AREA, CITY, VILLAGE, STREET) VALUES ('Минская область', 'Минск', '', 'Городской Вал');
    INSERT INTO ADDRESS_INFO (URBAN_AREA, CITY, VILLAGE, STREET) VALUES ('Минская область', 'Минск', '', 'Жуковского');
    INSERT INTO ADDRESS_INFO (URBAN_AREA, CITY, VILLAGE, STREET) VALUES ('Минская область', 'Минск', '', 'Артиллеристов');
    INSERT INTO ADDRESS_INFO (URBAN_AREA, CITY, VILLAGE, STREET) VALUES ('Минская область', 'Минск', '', 'Володько');
    INSERT INTO ADDRESS_INFO (URBAN_AREA, CITY, VILLAGE, STREET) VALUES ('Минская область', 'Минск', '', 'Бакинская');
    INSERT INTO ADDRESS_INFO (URBAN_AREA, CITY, VILLAGE, STREET) VALUES ('Минская область', 'Минск', '', 'Новоуфинская');
    INSERT INTO ADDRESS_INFO (URBAN_AREA, CITY, VILLAGE, STREET) VALUES ('Минская область', 'Минск', '', 'Левкова');
    INSERT INTO ADDRESS_INFO (URBAN_AREA, CITY, VILLAGE, STREET) VALUES ('Минская область', 'Минск', '', 'Аэродромная');
    INSERT INTO ADDRESS_INFO (URBAN_AREA, CITY, VILLAGE, STREET) VALUES ('Минская область', 'Минск', '', 'Немига');
    INSERT INTO ADDRESS_INFO (URBAN_AREA, CITY, VILLAGE, STREET) VALUES ('Минская область', 'Минск', '', 'Красная');
    INSERT INTO ADDRESS_INFO (URBAN_AREA, CITY, VILLAGE, STREET) VALUES ('Минская область', 'Минск', '', 'Раковская');
    INSERT INTO ADDRESS_INFO (URBAN_AREA, CITY, VILLAGE, STREET) VALUES ('Минская область', 'Минск', '', 'Ленина');
    INSERT INTO ADDRESS_INFO (URBAN_AREA, CITY, VILLAGE, STREET) VALUES ('Минская область', 'Минск', '', 'Сухая');
    INSERT INTO ADDRESS_INFO (URBAN_AREA, CITY, VILLAGE, STREET) VALUES ('Минская область', 'Минск', '', 'Первомайская');
    INSERT INTO ADDRESS_INFO (URBAN_AREA, CITY, VILLAGE, STREET) VALUES ('Минская область', 'Минск', '', 'Кальварийская');
    INSERT INTO ADDRESS_INFO (URBAN_AREA, CITY, VILLAGE, STREET) VALUES ('Минская область', 'Минск', '', 'Машерова');
    INSERT INTO ADDRESS_INFO (URBAN_AREA, CITY, VILLAGE, STREET) VALUES ('Минская область', 'Минск', '', 'Жуковского');
    INSERT INTO ADDRESS_INFO (URBAN_AREA, CITY, VILLAGE, STREET) VALUES ('Минская область', 'Минск', '', 'Веры Хоружей');
    INSERT INTO ADDRESS_INFO (URBAN_AREA, CITY, VILLAGE, STREET) VALUES ('Брестская область', 'Брест', '', 'Свободы');
    INSERT INTO ADDRESS_INFO (URBAN_AREA, CITY, VILLAGE, STREET) VALUES ('Брестская область', 'Брест', '', 'Бауманская');
    INSERT INTO ADDRESS_INFO (URBAN_AREA, CITY, VILLAGE, STREET) VALUES ('Брестская область', 'Брест', '', 'Сосновая');
    INSERT INTO ADDRESS_INFO (URBAN_AREA, CITY, VILLAGE, STREET) VALUES ('Брестская область', 'Брест', '', 'Голубая');
    INSERT INTO ADDRESS_INFO (URBAN_AREA, CITY, VILLAGE, STREET) VALUES ('Брестская область', 'Брест', '', 'Адамковская');
    INSERT INTO ADDRESS_INFO (URBAN_AREA, CITY, VILLAGE, STREET) VALUES ('Брестская область', 'Брест', '', 'Космонавтов');
    INSERT INTO ADDRESS_INFO (URBAN_AREA, CITY, VILLAGE, STREET) VALUES ('Брестская область', 'Брест', '', 'Дзержинского');
    INSERT INTO ADDRESS_INFO (URBAN_AREA, CITY, VILLAGE, STREET) VALUES ('Брестская область', 'Брест', '', 'Добрая');
    INSERT INTO ADDRESS_INFO (URBAN_AREA, CITY, VILLAGE, STREET) VALUES ('Брестская область', 'Брест', '', 'Грибоедова');
    INSERT INTO ADDRESS_INFO (URBAN_AREA, CITY, VILLAGE, STREET) VALUES ('Брестская область', 'Брест', '', 'Гаврилова');
    INSERT INTO ADDRESS_INFO (URBAN_AREA, CITY, VILLAGE, STREET) VALUES ('Брестская область', 'Брест', '', 'Алая');
    INSERT INTO ADDRESS_INFO (URBAN_AREA, CITY, VILLAGE, STREET) VALUES ('Брестская область', 'Брест', '', 'Дворцовая');
    INSERT INTO ADDRESS_INFO (URBAN_AREA, CITY, VILLAGE, STREET) VALUES ('Брестская область', 'Брест', '', 'Вычулки');
    INSERT INTO ADDRESS_INFO (URBAN_AREA, CITY, VILLAGE, STREET) VALUES ('Брестская область', 'Брест', '', 'Винника');
    INSERT INTO ADDRESS_INFO (URBAN_AREA, CITY, VILLAGE, STREET) VALUES ('Брестская область', 'Брест', '', 'Дворникова');
    INSERT INTO ADDRESS_INFO (URBAN_AREA, CITY, VILLAGE, STREET) VALUES ('Брестская область', 'Брест', '', 'Буденого');
    INSERT INTO ADDRESS_INFO (URBAN_AREA, CITY, VILLAGE, STREET) VALUES ('Могилёская область', 'Могилёв', '', 'Артиллерийская');
    INSERT INTO ADDRESS_INFO (URBAN_AREA, CITY, VILLAGE, STREET) VALUES ('Могилёская область', 'Могилёв', '', 'Архитектурная');
    INSERT INTO ADDRESS_INFO (URBAN_AREA, CITY, VILLAGE, STREET) VALUES ('Могилёская область', 'Могилёв', '', 'Альховская');
    INSERT INTO ADDRESS_INFO (URBAN_AREA, CITY, VILLAGE, STREET) VALUES ('Могилёская область', 'Могилёв', '', 'Мурманская');
    INSERT INTO ADDRESS_INFO (URBAN_AREA, CITY, VILLAGE, STREET) VALUES ('Могилёская область', 'Могилёв', '', 'Минина');
    INSERT INTO ADDRESS_INFO (URBAN_AREA, CITY, VILLAGE, STREET) VALUES ('Могилёская область', 'Могилёв', '', 'Майская');
    INSERT INTO ADDRESS_INFO (URBAN_AREA, CITY, VILLAGE, STREET) VALUES ('Могилёская область', 'Могилёв', '', 'Селянская');
    INSERT INTO ADDRESS_INFO (URBAN_AREA, CITY, VILLAGE, STREET) VALUES ('Могилёская область', 'Могилёв', '', 'Саперная');
    INSERT INTO ADDRESS_INFO (URBAN_AREA, CITY, VILLAGE, STREET) VALUES ('Могилёская область', 'Могилёв', '', 'Сибирский');
    INSERT INTO ADDRESS_INFO (URBAN_AREA, CITY, VILLAGE, STREET) VALUES ('Могилёская область', 'Могилёв', '', 'Дашковская');
    INSERT INTO ADDRESS_INFO (URBAN_AREA, CITY, VILLAGE, STREET) VALUES ('Могилёская область', 'Могилёв', '', 'Дружный');
    INSERT INTO ADDRESS_INFO (URBAN_AREA, CITY, VILLAGE, STREET) VALUES ('Могилёская область', 'Могилёв', '', 'Весенняя');
    INSERT INTO ADDRESS_INFO (URBAN_AREA, CITY, VILLAGE, STREET) VALUES ('Могилёская область', 'Могилёв', '', 'Вильчицкая');
    INSERT INTO ADDRESS_INFO (URBAN_AREA, CITY, VILLAGE, STREET) VALUES ('Могилёская область', 'Могилёв', '', 'Кашановская');
    INSERT INTO ADDRESS_INFO (URBAN_AREA, CITY, VILLAGE, STREET) VALUES ('Могилёская область', 'Могилёв', '', 'Кирова');
    INSERT INTO ADDRESS_INFO (URBAN_AREA, CITY, VILLAGE, STREET) VALUES ('Могилёская область', 'Могилёв', '', 'Карасева');
    INSERT INTO ADDRESS_INFO (URBAN_AREA, CITY, VILLAGE, STREET) VALUES ('Гомельская область', 'Гомель', '', 'Гагарина');
    INSERT INTO ADDRESS_INFO (URBAN_AREA, CITY, VILLAGE, STREET) VALUES ('Гомельская область', 'Гомель', '', 'Гастелло');
    INSERT INTO ADDRESS_INFO (URBAN_AREA, CITY, VILLAGE, STREET) VALUES ('Гомельская область', 'Гомель', '', 'Амурская');
    INSERT INTO ADDRESS_INFO (URBAN_AREA, CITY, VILLAGE, STREET) VALUES ('Гомельская область', 'Гомель', '', 'Димитрова');
    INSERT INTO ADDRESS_INFO (URBAN_AREA, CITY, VILLAGE, STREET) VALUES ('Гомельская область', 'Гомель', '', 'Дальняя');
    INSERT INTO ADDRESS_INFO (URBAN_AREA, CITY, VILLAGE, STREET) VALUES ('Гомельская область', 'Гомель', '', 'Амурская');
    INSERT INTO ADDRESS_INFO (URBAN_AREA, CITY, VILLAGE, STREET) VALUES ('Гомельская область', 'Гомель', '', 'Заводская');
    INSERT INTO ADDRESS_INFO (URBAN_AREA, CITY, VILLAGE, STREET) VALUES ('Гомельская область', 'Гомель', '', 'Жукова');
    INSERT INTO ADDRESS_INFO (URBAN_AREA, CITY, VILLAGE, STREET) VALUES ('Гомельская область', 'Гомель', '', 'Братская');
    INSERT INTO ADDRESS_INFO (URBAN_AREA, CITY, VILLAGE, STREET) VALUES ('Гомельская область', 'Гомель', '', 'Иногородная');
    INSERT INTO ADDRESS_INFO (URBAN_AREA, CITY, VILLAGE, STREET) VALUES ('Гомельская область', 'Гомель', '', 'Встречная');
    INSERT INTO ADDRESS_INFO (URBAN_AREA, CITY, VILLAGE, STREET) VALUES ('Гомельская область', 'Гомель', '', 'Иверская');
    INSERT INTO ADDRESS_INFO (URBAN_AREA, CITY, VILLAGE, STREET) VALUES ('Гомельская область', 'Гомель', '', 'Вишнёвая');
    INSERT INTO ADDRESS_INFO (URBAN_AREA, CITY, VILLAGE, STREET) VALUES ('Гомельская область', 'Гомель', '', 'Зелёная');
    INSERT INTO ADDRESS_INFO (URBAN_AREA, CITY, VILLAGE, STREET) VALUES ('Витебская область', 'Витебск', '', 'Громова');
    INSERT INTO ADDRESS_INFO (URBAN_AREA, CITY, VILLAGE, STREET) VALUES ('Витебская область', 'Витебск', '', 'Городокская');
    INSERT INTO ADDRESS_INFO (URBAN_AREA, CITY, VILLAGE, STREET) VALUES ('Витебская область', 'Витебск', '', 'Заводская');
    INSERT INTO ADDRESS_INFO (URBAN_AREA, CITY, VILLAGE, STREET) VALUES ('Витебская область', 'Витебск', '', 'Жлобинская');
    INSERT INTO ADDRESS_INFO (URBAN_AREA, CITY, VILLAGE, STREET) VALUES ('Витебская область', 'Витебск', '', 'Калининска');
    INSERT INTO ADDRESS_INFO (URBAN_AREA, CITY, VILLAGE, STREET) VALUES ('Витебская область', 'Витебск', '', 'Известковая');
    INSERT INTO ADDRESS_INFO (URBAN_AREA, CITY, VILLAGE, STREET) VALUES ('Витебская область', 'Витебск', '', 'Куйбышева');
    INSERT INTO ADDRESS_INFO (URBAN_AREA, CITY, VILLAGE, STREET) VALUES ('Витебская область', 'Витебск', '', 'Ольховая');
    INSERT INTO ADDRESS_INFO (URBAN_AREA, CITY, VILLAGE, STREET) VALUES ('Витебская область', 'Витебск', '', 'Октябрьская');
    INSERT INTO ADDRESS_INFO (URBAN_AREA, CITY, VILLAGE, STREET) VALUES ('Витебская область', 'Витебск', '', 'Полоцкая');
    INSERT INTO ADDRESS_INFO (URBAN_AREA, CITY, VILLAGE, STREET) VALUES ('Витебская область', 'Витебск', '', 'Полевая');
    INSERT INTO ADDRESS_INFO (URBAN_AREA, CITY, VILLAGE, STREET) VALUES ('Витебская область', 'Витебск', '', 'Пионерская');
    INSERT INTO ADDRESS_INFO (URBAN_AREA, CITY, VILLAGE, STREET) VALUES ('Гродненская область', 'Гродно', '', 'Грандичская');
    INSERT INTO ADDRESS_INFO (URBAN_AREA, CITY, VILLAGE, STREET) VALUES ('Гроднеская область', 'Гродно', '', 'Гоголя');
    INSERT INTO ADDRESS_INFO (URBAN_AREA, CITY, VILLAGE, STREET) VALUES ('Гродненская область', 'Гродно', '', 'Озерный');
    INSERT INTO ADDRESS_INFO (URBAN_AREA, CITY, VILLAGE, STREET) VALUES ('Гродненская область', 'Гродно', '', 'Ленина');
    INSERT INTO ADDRESS_INFO (URBAN_AREA, CITY, VILLAGE, STREET) VALUES ('Гродненская область', 'Гродно', '', 'Вишневецкая');
    INSERT INTO ADDRESS_INFO (URBAN_AREA, CITY, VILLAGE, STREET) VALUES ('Гродненская область', 'Гродно', '', 'Дарвина');
    INSERT INTO ADDRESS_INFO (URBAN_AREA, CITY, VILLAGE, STREET) VALUES ('Гродненская область', 'Гродно', '', 'Дубко');
    INSERT INTO ADDRESS_INFO (URBAN_AREA, CITY, VILLAGE, STREET) VALUES ('Гродненская область', 'Гродно', '', 'Западная');
    INSERT INTO ADDRESS_INFO (URBAN_AREA, CITY, VILLAGE, STREET) VALUES ('Гродненская область', 'Гродно', '', 'Волкова');
    INSERT INTO ADDRESS_INFO (URBAN_AREA, CITY, VILLAGE, STREET) VALUES ('Гродненская область', 'Гродно', '', 'Доватора');
    INSERT INTO ADDRESS_INFO (URBAN_AREA, CITY, VILLAGE, STREET) VALUES ('Гродненская область', 'Гродно', '', 'Мясницкая');
    INSERT INTO ADDRESS_INFO (URBAN_AREA, CITY, VILLAGE, STREET) VALUES ('Минская область', '', 'Лесковка', 'Центральная');
    INSERT INTO ADDRESS_INFO (URBAN_AREA, CITY, VILLAGE, STREET) VALUES ('Минская область', '', 'Скураты', 'Луговая');
    INSERT INTO ADDRESS_INFO (URBAN_AREA, CITY, VILLAGE, STREET) VALUES ('Минская область', '', 'Воловщина', 'Болотная');
    INSERT INTO ADDRESS_INFO (URBAN_AREA, CITY, VILLAGE, STREET) VALUES ('Минская область', '', 'Капличи', 'Лесная');
    INSERT INTO ADDRESS_INFO (URBAN_AREA, CITY, VILLAGE, STREET) VALUES ('Минская область', '', 'Черники', 'Городская');
    INSERT INTO ADDRESS_INFO (URBAN_AREA, CITY, VILLAGE, STREET) VALUES ('Минская область', '', 'Горошки', 'Филимонова');
    INSERT INTO ADDRESS_INFO (URBAN_AREA, CITY, VILLAGE, STREET) VALUES ('Витебская область', '', 'Витьба', 'Дубовая');
    INSERT INTO ADDRESS_INFO (URBAN_AREA, CITY, VILLAGE, STREET) VALUES ('Витебская область', '', 'Максютки', 'Основная');
    INSERT INTO ADDRESS_INFO (URBAN_AREA, CITY, VILLAGE, STREET) VALUES ('Витебская область', '', 'Кашино', 'Землянная');
    INSERT INTO ADDRESS_INFO (URBAN_AREA, CITY, VILLAGE, STREET) VALUES ('Витебская область', '', 'Вороны', 'Ленина');
    INSERT INTO ADDRESS_INFO (URBAN_AREA, CITY, VILLAGE, STREET) VALUES ('Витебская область', '', 'Бабиничи', 'Победы');
    INSERT INTO ADDRESS_INFO (URBAN_AREA, CITY, VILLAGE, STREET) VALUES ('Витебская область', '', 'Фокино', 'Победы');
    INSERT INTO ADDRESS_INFO (URBAN_AREA, CITY, VILLAGE, STREET) VALUES ('Витебская область', '', 'Мишутки', 'Центральная');
    INSERT INTO ADDRESS_INFO (URBAN_AREA, CITY, VILLAGE, STREET) VALUES ('Витебская область', '', 'Гунченки', 'Городская');
    INSERT INTO ADDRESS_INFO (URBAN_AREA, CITY, VILLAGE, STREET) VALUES ('Гомельская область', '', 'Цыкуны', 'Центральная');
    INSERT INTO ADDRESS_INFO (URBAN_AREA, CITY, VILLAGE, STREET) VALUES ('Гомельская область', '', 'Баштан', 'Московская');
    INSERT INTO ADDRESS_INFO (URBAN_AREA, CITY, VILLAGE, STREET) VALUES ('Гомельская область', '', 'Азделино', 'Речная');
    INSERT INTO ADDRESS_INFO (URBAN_AREA, CITY, VILLAGE, STREET) VALUES ('Гомельская область', '', 'Песочная Буда', 'Зелёная');
    INSERT INTO ADDRESS_INFO (URBAN_AREA, CITY, VILLAGE, STREET) VALUES ('Гомельская область', '', 'Климовский', 'Зелёная');
    INSERT INTO ADDRESS_INFO (URBAN_AREA, CITY, VILLAGE, STREET) VALUES ('Гомельская область', '', 'Межи', 'Московская');
    INSERT INTO ADDRESS_INFO (URBAN_AREA, CITY, VILLAGE, STREET) VALUES ('Гомельская область', '', 'Василево', 'Ленина');
    INSERT INTO ADDRESS_INFO (URBAN_AREA, CITY, VILLAGE, STREET) VALUES ('Брестская область', '', 'Липинки', 'Красная');
    INSERT INTO ADDRESS_INFO (URBAN_AREA, CITY, VILLAGE, STREET) VALUES ('Брестская область', '', 'Богданы', 'Луговая');
    INSERT INTO ADDRESS_INFO (URBAN_AREA, CITY, VILLAGE, STREET) VALUES ('Брестская область', '', 'Бернады', 'Луговая');
    INSERT INTO ADDRESS_INFO (URBAN_AREA, CITY, VILLAGE, STREET) VALUES ('Брестская область', '', 'Клейники', 'Лесная');
    INSERT INTO ADDRESS_INFO (URBAN_AREA, CITY, VILLAGE, STREET) VALUES ('Брестская область', '', 'Берестье', 'Победы');
    INSERT INTO ADDRESS_INFO (URBAN_AREA, CITY, VILLAGE, STREET) VALUES ('Брестская область', '', 'Волки', 'Красная');
    INSERT INTO ADDRESS_INFO (URBAN_AREA, CITY, VILLAGE, STREET) VALUES ('Могилёская область', '', 'Дубинка', 'Ленина');
    INSERT INTO ADDRESS_INFO (URBAN_AREA, CITY, VILLAGE, STREET) VALUES ('Могилёская область', '', 'Новоселки', 'Земская');
    INSERT INTO ADDRESS_INFO (URBAN_AREA, CITY, VILLAGE, STREET) VALUES ('Могилёская область', '', 'Сташино', 'Хоружей');
    INSERT INTO ADDRESS_INFO (URBAN_AREA, CITY, VILLAGE, STREET) VALUES ('Могилёская область', '', 'Понизов', 'Максима Танка');
    INSERT INTO ADDRESS_INFO (URBAN_AREA, CITY, VILLAGE, STREET) VALUES ('Могилёская область', '', 'Затишье', 'Горецкого');
    INSERT INTO ADDRESS_INFO (URBAN_AREA, CITY, VILLAGE, STREET) VALUES ('Гродненская область', '', 'Тужевляны', 'Круговая');
    INSERT INTO ADDRESS_INFO (URBAN_AREA, CITY, VILLAGE, STREET) VALUES ('Гродненская область', '', 'Криничная', 'Красная');
    INSERT INTO ADDRESS_INFO (URBAN_AREA, CITY, VILLAGE, STREET) VALUES ('Гродненская область', '', 'Завадичи', 'Победы');
    INSERT INTO ADDRESS_INFO (URBAN_AREA, CITY, VILLAGE, STREET) VALUES ('Гродненская область', '', 'Бояры', 'Центральная');
    INSERT INTO ADDRESS_INFO (URBAN_AREA, CITY, VILLAGE, STREET) VALUES ('Гродненская область', '', 'Луцковляны', 'Ленина');
    INSERT INTO ADDRESS_INFO (URBAN_AREA, CITY, VILLAGE, STREET) VALUES ('Гродненская область', '', 'Цидовичи', 'Военная');
END;

COMMIT;

CREATE OR REPLACE FUNCTION RAND_CITY
RETURN NVARCHAR2
IS 
FCITY NVARCHAR2(30);
BEGIN
SELECT CITY INTO FCITY FROM(
SELECT CITY FROM ADDRESS_INFO
WHERE CITY IS NOT NULL
ORDER BY DBMS_RANDOM.RANDOM)
FETCH FIRST 1 ROW ONLY;
RETURN FCITY;
END;
/
CREATE OR REPLACE FUNCTION RAND_STREET(FCITY NVARCHAR2)
RETURN NVARCHAR2
IS 
FSTREET NVARCHAR2(30);
BEGIN
SELECT STREET INTO FSTREET FROM(
SELECT STREET FROM ADDRESS_INFO
WHERE CITY LIKE FCITY
ORDER BY DBMS_RANDOM.RANDOM)
FETCH FIRST 1 ROW ONLY;
RETURN FSTREET;
END;
/
CREATE OR REPLACE FUNCTION RAND_ADDRESS 
RETURN NVARCHAR2
IS
ADDRESS NVARCHAR2(100);
RNUM NUMBER;
FCITY NVARCHAR2(50);
BEGIN
FCITY := RAND_CITY();
SELECT DBMS_RANDOM.VALUE(1, 100) NUM INTO RNUM FROM DUAL;
RNUM := ROUND(RNUM);
ADDRESS := CONCAT('г. ', CONCAT(FCITY, CONCAT(', ', CONCAT(RAND_STREET(FCITY), CONCAT(' ', RNUM)))));
RETURN ADDRESS;
END;

COMMIT;



CREATE TABLE TYPE_TRAININGS
(
    NAME_TYPE NVARCHAR2(50)
);


BEGIN
    INSERT INTO TYPE_TRAININGS(NAME_TYPE) VALUES('Йога');
    INSERT INTO TYPE_TRAININGS(NAME_TYPE) VALUES('Тайцзи');
    INSERT INTO TYPE_TRAININGS(NAME_TYPE) VALUES('Пилатес');
    INSERT INTO TYPE_TRAININGS(NAME_TYPE) VALUES('Цигун');
    INSERT INTO TYPE_TRAININGS(NAME_TYPE) VALUES('Каларипаятту');
    INSERT INTO TYPE_TRAININGS(NAME_TYPE) VALUES('Будокон');
    INSERT INTO TYPE_TRAININGS(NAME_TYPE) VALUES('Танцевальная аэробика');
    INSERT INTO TYPE_TRAININGS(NAME_TYPE) VALUES('Байлотерапия');
    INSERT INTO TYPE_TRAININGS(NAME_TYPE) VALUES('Стрип-пластика');
    INSERT INTO TYPE_TRAININGS(NAME_TYPE) VALUES('Pole-Аnce');
    INSERT INTO TYPE_TRAININGS(NAME_TYPE) VALUES('Шейпинг');
    INSERT INTO TYPE_TRAININGS(NAME_TYPE) VALUES('Аэробика');
    INSERT INTO TYPE_TRAININGS(NAME_TYPE) VALUES('Степ-аэробика');
    INSERT INTO TYPE_TRAININGS(NAME_TYPE) VALUES('Сайкл');
    INSERT INTO TYPE_TRAININGS(NAME_TYPE) VALUES('Фитбол и босу');
    INSERT INTO TYPE_TRAININGS(NAME_TYPE) VALUES('Аквааэробика');
    INSERT INTO TYPE_TRAININGS(NAME_TYPE) VALUES('Тай-бо');
    INSERT INTO TYPE_TRAININGS(NAME_TYPE) VALUES('Кроссфит');
    INSERT INTO TYPE_TRAININGS(NAME_TYPE) VALUES('Body Sculpt');
    INSERT INTO TYPE_TRAININGS(NAME_TYPE) VALUES('Аэробика');
    INSERT INTO TYPE_TRAININGS(NAME_TYPE) VALUES('Бодипамп');
    INSERT INTO TYPE_TRAININGS(NAME_TYPE) VALUES('Стретчинг');
    INSERT INTO TYPE_TRAININGS(NAME_TYPE) VALUES('Калланетика');
    INSERT INTO TYPE_TRAININGS(NAME_TYPE) VALUES('Бодифлекс');
    INSERT INTO TYPE_TRAININGS(NAME_TYPE) VALUES('Circuit Training');
    INSERT INTO TYPE_TRAININGS(NAME_TYPE) VALUES('Interval HIIT');
    INSERT INTO TYPE_TRAININGS(NAME_TYPE) VALUES('Functional Training');
    INSERT INTO TYPE_TRAININGS(NAME_TYPE) VALUES('TRX');
END;

    CREATE OR REPLACE FUNCTION RAND_TYPE_TRAINING
    RETURN NVARCHAR2
    IS 
    FTYPE_TRAININGS NVARCHAR2(50);
    BEGIN
    SELECT NAME_TYPE INTO FTYPE_TRAININGS FROM(
    SELECT NAME_TYPE FROM TYPE_TRAININGS
    ORDER BY DBMS_RANDOM.RANDOM)
    FETCH FIRST 1 ROW ONLY;
    RETURN FTYPE_TRAININGS;
    END;
    
    CREATE TABLE TYPE_SERVICES
    (
        NAME_TYPES NVARCHAR2(50)
    );
    
    BEGIN
        INSERT INTO TYPE_SERVICES(NAME_TYPES) VALUES ('Талассотерапия');
        INSERT INTO TYPE_SERVICES(NAME_TYPES) VALUES ('Бальнеотерапия');
        INSERT INTO TYPE_SERVICES(NAME_TYPES) VALUES ('Ароматерапия');
        INSERT INTO TYPE_SERVICES(NAME_TYPES) VALUES ('Диагностика');
        INSERT INTO TYPE_SERVICES(NAME_TYPES) VALUES ('Ванны с грязями и морскими водорослями');
        INSERT INTO TYPE_SERVICES(NAME_TYPES) VALUES ('Воздушно-пузырьковые ванны');
        INSERT INTO TYPE_SERVICES(NAME_TYPES) VALUES ('Массаж');
        INSERT INTO TYPE_SERVICES(NAME_TYPES) VALUES ('Мануальнаю терапия');
        INSERT INTO TYPE_SERVICES(NAME_TYPES) VALUES ('Гидромассаж');
        INSERT INTO TYPE_SERVICES(NAME_TYPES) VALUES ('Бассейн');
        INSERT INTO TYPE_SERVICES(NAME_TYPES) VALUES ('Макияж');
        INSERT INTO TYPE_SERVICES(NAME_TYPES) VALUES ('Маникюр');
        INSERT INTO TYPE_SERVICES(NAME_TYPES) VALUES ('Педикюр');
        INSERT INTO TYPE_SERVICES(NAME_TYPES) VALUES ('Теплолечения');
        INSERT INTO TYPE_SERVICES(NAME_TYPES) VALUES ('Светолечения');
        INSERT INTO TYPE_SERVICES(NAME_TYPES) VALUES ('Электрофореза');
        INSERT INTO TYPE_SERVICES(NAME_TYPES) VALUES ('Гальванизация');
    END;
    
    CREATE OR REPLACE FUNCTION RAND_TYPE_SERVICES
    RETURN NVARCHAR2
    IS 
    FTYPE_SERVICES NVARCHAR2(50);
    BEGIN
    SELECT NAME_TYPES INTO FTYPE_SERVICES FROM(
    SELECT NAME_TYPES FROM TYPE_SERVICES
    ORDER BY DBMS_RANDOM.RANDOM)
    FETCH FIRST 1 ROW ONLY;
    RETURN FTYPE_SERVICES;
    END;
    
    CREATE OR REPLACE FUNCTION RPRICE
    RETURN NUMBER
    IS
    FPRICE NUMBER;
    BEGIN
        SELECT DBMS_RANDOM.VALUE(800, 4500) NUM INTO FPRICE FROM DUAL;
        FPRICE := ROUND(FPRICE, -2);
        RETURN FPRICE;
    END;
    
    CREATE OR REPLACE FUNCTION AMOUNTVISIT
    RETURN NUMBER
    IS
    COUNTVISIT NUMBER;
    BEGIN
        SELECT DBMS_RANDOM.VALUE(7, 28) NUM INTO COUNTVISIT FROM DUAL;
        COUNTVISIT := ROUND(COUNTVISIT);
        RETURN COUNTVISIT;
    END;
    
    CREATE OR REPLACE FUNCTION AMOUNTDAYS
    RETURN NUMBER
    IS
    COUNTDAYS NUMBER;
    BEGIN
        SELECT DBMS_RANDOM.VALUE(1, 30) NUM INTO COUNTDAYS FROM DUAL;
        COUNTDAYS := ROUND(COUNTDAYS);
        RETURN COUNTDAYS;
    END;
    
    CREATE OR REPLACE FUNCTION AMOUNTMONTHS
    RETURN NUMBER
    IS
    COUNTMONTHS NUMBER;
    BEGIN
        SELECT DBMS_RANDOM.VALUE(1, 12) NUM INTO COUNTMONTHS FROM DUAL;
        COUNTMONTHS := ROUND(COUNTMONTHS);
        RETURN COUNTMONTHS;
    END;
    
    
    
   
    
CREATE OR REPLACE FUNCTION ID_CLIENTS
RETURN NUMBER
IS
COUNTIDCLIENTS NUMBER;
BEGIN
    SELECT DBMS_RANDOM.VALUE(1, 40000) NUM INTO COUNTIDCLIENTS FROM DUAL;
    COUNTIDCLIENTS := ROUND(COUNTIDCLIENTS);
    RETURN COUNTIDCLIENTS;
END;
    
    
    CREATE OR REPLACE FUNCTION ID_ABONEMENTS
    RETURN NUMBER
    IS
    COUNTIDABONEMENTS NUMBER;
    BEGIN
        SELECT DBMS_RANDOM.VALUE(1, 40000) NUM INTO COUNTIDABONEMENTS FROM DUAL;
        COUNTIDABONEMENTS := ROUND(COUNTIDABONEMENTS);
        RETURN COUNTIDABONEMENTS;
    END;
    
    
CREATE OR REPLACE FUNCTION RTIME(FSTART DATE, FEND DATE)
RETURN DATE
IS
FTIME DATE;
BEGIN
SELECT TO_DATE(TRUNC(DBMS_RANDOM.VALUE(
TO_CHAR(TO_DATE(FSTART,'dd-mm-yyyy'), 'J'),
TO_CHAR(TO_DATE(FEND,'dd-mm-yyyy'), 'J'))),'J')
INTO FTIME FROM DUAL;
RETURN FTIME;
END;


CREATE OR REPLACE FUNCTION ID_SALE
RETURN NUMBER
IS
    COUNTID_CARD NUMBER;
BEGIN
   SELECT DBMS_RANDOM.VALUE(1, 40000) NUM INTO COUNTID_CARD FROM DUAL;
    COUNTID_CARD := ROUND(COUNTID_CARD);
    RETURN COUNTID_CARD;
END;

CREATE OR REPLACE FUNCTION NUMBER_RECORD
RETURN NUMBER
IS
    COUNTNUMBER_RECORD NUMBER;
BEGIN
   SELECT DBMS_RANDOM.VALUE(1, 40000) NUM INTO COUNTNUMBER_RECORD FROM DUAL;
    COUNTNUMBER_RECORD := ROUND(COUNTNUMBER_RECORD);
    RETURN COUNTNUMBER_RECORD;
END;


CREATE OR REPLACE FUNCTION ID_COMPLEXES
RETURN NUMBER
IS
    COUNTID_COMPLEXES NUMBER;
BEGIN
    SELECT DBMS_RANDOM.VALUE(1, 40000) NUM INTO COUNTID_COMPLEXES FROM DUAL;
    COUNTID_COMPLEXES := ROUND(COUNTID_COMPLEXES);
    RETURN COUNTID_COMPLEXES;
END;



CREATE TABLE NAME_COMPLEXES
(
    NAME_COMPLEX NVARCHAR2(50)
);

BEGIN
    INSERT INTO NAME_COMPLEXES(NAME_COMPLEX) VALUES('Здоровье и гармония');
    INSERT INTO NAME_COMPLEXES(NAME_COMPLEX) VALUES('Солнечный берег');
    INSERT INTO NAME_COMPLEXES(NAME_COMPLEX) VALUES('Русская баня');
    INSERT INTO NAME_COMPLEXES(NAME_COMPLEX) VALUES('Лесной край');
    INSERT INTO NAME_COMPLEXES(NAME_COMPLEX) VALUES('Золотой ключик');
    INSERT INTO NAME_COMPLEXES(NAME_COMPLEX) VALUES('Белый камень');
    INSERT INTO NAME_COMPLEXES(NAME_COMPLEX) VALUES('Лазурный берег');
    INSERT INTO NAME_COMPLEXES(NAME_COMPLEX) VALUES('Санаторий им. Ленина');
    INSERT INTO NAME_COMPLEXES(NAME_COMPLEX) VALUES('Березка');
    INSERT INTO NAME_COMPLEXES(NAME_COMPLEX) VALUES('Здоровье и успех');
    INSERT INTO NAME_COMPLEXES(NAME_COMPLEX) VALUES('Горный воздух');
    INSERT INTO NAME_COMPLEXES(NAME_COMPLEX) VALUES('Сосновый бор');
    INSERT INTO NAME_COMPLEXES(NAME_COMPLEX) VALUES('Лечебный курорт');
    INSERT INTO NAME_COMPLEXES(NAME_COMPLEX) VALUES('Лесная поляна');
    INSERT INTO NAME_COMPLEXES(NAME_COMPLEX) VALUES('Здоровье и красота');
END;

    CREATE OR REPLACE FUNCTION RAND_NAME_COMPLEX
    RETURN NVARCHAR2
    IS 
        NAMECOMPLEX NVARCHAR2(50);
    BEGIN
        SELECT NAME_COMPLEX INTO NAMECOMPLEX FROM(
        SELECT NAME_COMPLEX FROM NAME_COMPLEXES
        ORDER BY DBMS_RANDOM.RANDOM)
        FETCH FIRST 1 ROW ONLY;
        RETURN NAMECOMPLEX;
    END;

CREATE OR REPLACE FUNCTION CAPACITY_C
RETURN NUMBER
IS
    COUNTCAPACITY NUMBER;
BEGIN
   SELECT DBMS_RANDOM.VALUE(30, 50) NUM INTO COUNTCAPACITY FROM DUAL;
    COUNTCAPACITY := ROUND(COUNTCAPACITY);
    RETURN COUNTCAPACITY;
END;

CREATE TABLE TIME_BEGIN
(
    TIME_BEGINS NVARCHAR2(30)
);

BEGIN
    INSERT INTO TIME_BEGIN(TIME_BEGINS) VALUES ('7:00');
    INSERT INTO TIME_BEGIN(TIME_BEGINS) VALUES ('7:30');
    INSERT INTO TIME_BEGIN(TIME_BEGINS) VALUES ('8:00');
    INSERT INTO TIME_BEGIN(TIME_BEGINS) VALUES ('8:30');
    INSERT INTO TIME_BEGIN(TIME_BEGINS) VALUES ('9:25');
    INSERT INTO TIME_BEGIN(TIME_BEGINS) VALUES ('9:50');
    INSERT INTO TIME_BEGIN(TIME_BEGINS) VALUES ('10:10');
    INSERT INTO TIME_BEGIN(TIME_BEGINS) VALUES ('10:45');
    INSERT INTO TIME_BEGIN(TIME_BEGINS) VALUES ('11:15');
    INSERT INTO TIME_BEGIN(TIME_BEGINS) VALUES ('11:35');
    INSERT INTO TIME_BEGIN(TIME_BEGINS) VALUES ('12:00');
    INSERT INTO TIME_BEGIN(TIME_BEGINS) VALUES ('12:15');
    INSERT INTO TIME_BEGIN(TIME_BEGINS) VALUES ('12:55');
    INSERT INTO TIME_BEGIN(TIME_BEGINS) VALUES ('13:35');
    INSERT INTO TIME_BEGIN(TIME_BEGINS) VALUES ('14:05');
    INSERT INTO TIME_BEGIN(TIME_BEGINS) VALUES ('14:45');
    INSERT INTO TIME_BEGIN(TIME_BEGINS) VALUES ('15:00');
END;

    CREATE OR REPLACE FUNCTION RAND_TIME_BEGIN
    RETURN NVARCHAR2
    IS 
        TIMEISBEGIN NVARCHAR2(50);
    BEGIN
        SELECT TIME_BEGINS INTO TIMEISBEGIN FROM(
        SELECT TIME_BEGINS FROM TIME_BEGIN
        ORDER BY DBMS_RANDOM.RANDOM)
        FETCH FIRST 1 ROW ONLY;
        RETURN TIMEISBEGIN;
    END;

CREATE TABLE TIME_END
(
    TIME_ENDS NVARCHAR2(50)
)


BEGIN
    INSERT INTO TIME_END(TIME_ENDS) VALUES ('15:30');
    INSERT INTO TIME_END(TIME_ENDS) VALUES ('15:45');
    INSERT INTO TIME_END(TIME_ENDS) VALUES ('16:25');
    INSERT INTO TIME_END(TIME_ENDS) VALUES ('16:55');
    INSERT INTO TIME_END(TIME_ENDS) VALUES ('17:15');
    INSERT INTO TIME_END(TIME_ENDS) VALUES ('17:55');
    INSERT INTO TIME_END(TIME_ENDS) VALUES ('18:05');
    INSERT INTO TIME_END(TIME_ENDS) VALUES ('18:50');
    INSERT INTO TIME_END(TIME_ENDS) VALUES ('19:00');
    INSERT INTO TIME_END(TIME_ENDS) VALUES ('19:40');
    INSERT INTO TIME_END(TIME_ENDS) VALUES ('20:20');
    INSERT INTO TIME_END(TIME_ENDS) VALUES ('20:45');
    INSERT INTO TIME_END(TIME_ENDS) VALUES ('21:00');
END;

    CREATE OR REPLACE FUNCTION RAND_TIME_END
    RETURN NVARCHAR2
    IS 
        TIMEISEND NVARCHAR2(50);
    BEGIN
        SELECT TIME_ENDS INTO TIMEISEND FROM(
        SELECT TIME_ENDS FROM TIME_END
        ORDER BY DBMS_RANDOM.RANDOM)
        FETCH FIRST 1 ROW ONLY;
        RETURN TIMEISEND;
    END;
    
    
CREATE OR REPLACE FUNCTION ID_EMPLOYEE
RETURN NUMBER
IS
    COUNTID_EMPLOYEE NUMBER;
BEGIN
   SELECT DBMS_RANDOM.VALUE(1, 100) NUM INTO COUNTID_EMPLOYEE FROM DUAL;
    COUNTID_EMPLOYEE := ROUND(COUNTID_EMPLOYEE);
    RETURN COUNTID_EMPLOYEE;
END;

CREATE OR REPLACE FUNCTION ID_SERVICES
RETURN NUMBER
IS
    COUNTID_SERVICES NUMBER;
BEGIN
   SELECT DBMS_RANDOM.VALUE(1, 100) NUM INTO COUNTID_SERVICES FROM DUAL;
    COUNTID_SERVICES := ROUND(COUNTID_SERVICES);
    RETURN COUNTID_SERVICES;
END;

CREATE OR REPLACE FUNCTION ID_TRAINING
RETURN NUMBER
IS
    COUNTID_TRAINING NUMBER;
BEGIN
   SELECT DBMS_RANDOM.VALUE(1, 100) NUM INTO COUNTID_TRAINING FROM DUAL;
    COUNTID_TRAINING := ROUND(COUNTID_TRAINING);
    RETURN COUNTID_TRAINING;
END;

    CREATE OR REPLACE FUNCTION RSALARY
    RETURN NUMBER
    IS
    FSALARY NUMBER;
    BEGIN
        SELECT DBMS_RANDOM.VALUE(700, 2500) NUM INTO FSALARY FROM DUAL;
        FSALARY := ROUND(FSALARY, -2);
        RETURN FSALARY;
    END;